version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019 Preview
shallow_clone: true
before_build:
  - nuget restore
build:
  project: BindingNavigator.Wpf.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: '\NetFramework\BindingNavigator\bin\Release\BindingNavigator.dll'
  name: BindingNavigator.dll
- path: '\Core\BindingNavigator\bin\Debug\netcoreapp3.1\BindingNavigator.NetCore.dll'
  name: BindingNavigator.NetCore.dll
deploy:
- provider: NuGet
  api_key:
    secure: /qDdlDopI8PSfoElwGykgg==
  skip_symbols: true
  on:
    branch: master